apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mnist-classifier
  name: mnist-classifier
spec:
  selector:
    matchLabels:
      app: mnist-classifier
  template:
    metadata:
      labels:
        app: mnist-classifier
    spec:
      containers:
        - image: gcr.io/abstract-flame-330901/mnist_classifier_bentoml:95140b94
          imagePullPolicy: IfNotPresent
          name: mnist-classifier
          ports:
            - containerPort: 5000
