apiVersion: v1
kind: Service
metadata:
  labels:
    app: mnist-classifier
  name: mnist-classifier
spec:
  ports:
    - name: predict
      port: 5000
      targetPort: 5000
  selector:
    app: mnist-classifier
  type: LoadBalancer
