apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-train-job
  namespace: mnist
spec:
  template:
    spec:
      containers:
        - name: mnist-train
          image: gcr.io/abstract-flame-330901/mnist_train
          args:
            [
              "--ACCESS_TOKEN",
              "access-token",
              "--num_neurons",
              "128",
              "--learning_rate",
              "0.001",
              "--output_model_path",
              "gs://suwan/mnist_model_demo2",
            ]
      restartPolicy: Never
  backoffLimit: 4
